### PR TITLE
all: implement return action and execTemplate func

### PR DESCRIPTION
**Pull request by jo3-l**
**Note**
You may want to only look at [this commit](https://github.com/jonas747/template/pull/6/commits/3d483dcfe954e9a1ca04c28bfb0f91e12c40b3cf) during review as the rest is just noise from having the commits from havin #4 in here too.

**Description**
This implements `execTemplate` and `return`. `return` stops execution of the current template and returns the result to the caller. The return value can be retrieved through calling the `execTemplate` function.

**Status**
All tests pass, except the newline ones mentioned earlier.

### CODE REVIEW

**Comment by jo3-l** [comment]
I might've broke git history on my local copy of this PR... uhh, will fix / open a new PR when I get back. Ignore for now.

**Comment by jo3-l** [comment]
Re-drafting this for now. See https://github.com/jonas747/template/pull/4#issuecomment-855465657.

**Comment by ashishjh-bst** [comment]
Has conflicts after the try catch and while features have been merged @jo3-l

**Comment by jo3-l** [comment]
Rebased.

**Pull request merged**
